[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php artisan migrate --force && php -S 0.0.0.0:$PORT -t public"

[phases.setup]
phpPkgs = ["php", "php-gd", "composer"]